name: gonavis-franchising
recipe: pantheon
config:
  framework: drupal8
  site: gonavis-franchising
  id: bd2040d9-444e-4c2e-ad13-fd575701973a
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
  drush:
    cmd:
      - "/app/vendor/bin/drush"
      - "--root=/app/web"
